name: Auto message on pr merge

on:
  pull_request_target:
    types: [closed]

jobs:
  auto-response:
    runs-on: ubuntu-latest

    steps:
    - uses: derekprior/add-autoresponse@master
      env:
        F_W_P: ${{ secrets.F_W_P }}
      with:
        respondableId: ${{ github.event.pull_request.node_id }}
        response: "Thank you @${{ github.event.pull_request.user.login }} for taking out your valuable time in order to contribute to our project. Looking forward for more such amazing contributions :)"
        author: ${{ github.event.pull_request.user.login }}
        exemptedAuthors: "Amit366"